services:

  react-chatgpt:
    container_name: react-chatgpt
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_OPENAI_API_KEY= <YOUR OPENAI KEY>
    command: npm start